name: Python CI

on: 
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        arch: [ X64 ]
      fail-fast: false

    runs-on: [ self-hosted, "${{matrix.arch}}" ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure
      shell: bash
      run: |
        cd ../build
        rm -rf *
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_TOOLCHAIN_FILE=../ydb/clang.toolchain ../ydb
    - name: Build
      shell: bash
      run: |
        cd ../build
        ninja
    - name: Test
      shell: bash
      run: |
        export source_root=~/actions-runner/_work/ydb/ydb/
        export build_root=~/actions-runner/_work/ydb/build/
        rm -rf ${source_root}/ydb/tests/functional/test-results/*
        source ${source_root}/ydb/tests/oss/launch/prepare.sh
        python ${source_root}/ydb/tests/oss/launch/launch.py --test-dir ${source_root}/ydb/tests/functional \
          --xml-dir ${source_root}/ydb/tests/functional/test-results/xml
