name: Nightly-run
on: 
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      test_label_regexp:
        required: false
        type: string
      launch_unit_tests:
        required: false
        type: boolean
        default: true
      launch_functional_tests:
        required: false
        type: boolean
        default: true
  
jobs:
  build_ondemand:
    name: Build/test X64
    strategy:
      matrix:
        sanitizer: [ "", "sanitize=address" ]
      fail-fast: false

    uses: ./.github/workflows/build_and_test_ondemand.yml
    with:
      sanitizer: ${{matrix.sanitizer}}
      test_label_regexp: ${{inputs.test_label_regexp}}
    secrets: inherit

  build_provisioned:
    name: Build/test ARM64
    strategy:
      matrix:
        sanitizer: [ "", "sanitize=address" ]
      fail-fast: false
    uses: ./.github/workflows/My_build_and_test_provisioned.yml
    with:
      runner_label: ARM64
      sanitizer: ${{matrix.sanitizer}}
      test_label_regexp: ${{inputs.test_label_regexp}}
      launch_unit_tests: ${{inputs.launch_unit_tests}}
      launch_functional_tests: ${{inputs.launch_functional_tests}}
    secrets: inherit